# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170818_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
