# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('developer', 'DEVELOPER'), ('designer', 'DESIGNER'), ('management', 'MANAGEMENT')], default='developer', max_length=35),
        ),
    ]
