# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170816_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('management', 'Management')], default='developer', max_length=35),
        ),
    ]
