# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170818_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=225)),
                ('position', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('management', 'Management')], default='developer', max_length=35)),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
